/**
 * Self-host the Google Fonts used by the site.
 *
 * Fetches the css2 stylesheet for each family (with a modern browser UA so we
 * get woff2), downloads the latin / latin-ext subsets into /fonts, and writes
 * fonts/fonts.css with @font-face rules pointing at the local files.
 *
 * The @font-face block is then pasted into the top of styles.css (done once;
 * fonts rarely change). Re-run with: npm run gen:fonts
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FONTS_DIR = resolve(__dirname, "../fonts");

// Only ship the subsets an English-only site needs (latin covers € and common
// accents; latin-ext adds the rest of European Latin for safety).
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

const FAMILIES = [
  { name: "Plus Jakarta Sans", weights: [400, 500, 600, 700, 800] },
  { name: "IBM Plex Mono", weights: [400, 500, 600] },
];

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

const BLOCK_RE = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
const pick = (block, re) => (block.match(re) || [])[1];

async function main() {
  await mkdir(FONTS_DIR, { recursive: true });
  const faces = [];

  for (const fam of FAMILIES) {
    const url =
      "https://fonts.googleapis.com/css2?family=" +
      encodeURIComponent(fam.name).replace(/%20/g, "+") +
      ":wght@" + fam.weights.join(";") + "&display=swap";

    const css = await (await fetch(url, { headers: { "User-Agent": UA } })).text();

    let m;
    while ((m = BLOCK_RE.exec(css))) {
      const subset = m[1];
      const block = m[2];
      if (!KEEP_SUBSETS.has(subset)) continue;

      const family = pick(block, /font-family:\s*'([^']+)'/);
      const weight = pick(block, /font-weight:\s*(\d+)/);
      const style = pick(block, /font-style:\s*(\w+)/) || "normal";
      const src = pick(block, /src:\s*url\(([^)]+)\)/);
      const range = pick(block, /unicode-range:\s*([^;]+);/);
      if (!family || !src) continue;

      const file = `${slug(family)}-${weight}-${subset}.woff2`;
      const buf = Buffer.from(await (await fetch(src, { headers: { "User-Agent": UA } })).arrayBuffer());
      await writeFile(resolve(FONTS_DIR, file), buf);
      console.log(`  ↓ ${file} (${(buf.length / 1024).toFixed(1)} KB)`);

      faces.push(
        `@font-face {\n` +
          `  font-family: '${family}';\n` +
          `  font-style: ${style};\n` +
          `  font-weight: ${weight};\n` +
          `  font-display: swap;\n` +
          `  src: url('/fonts/${file}') format('woff2');\n` +
          (range ? `  unicode-range: ${range};\n` : "") +
          `}`
      );
    }
  }

  const header =
    "/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs.\n" +
    "   Plus Jakarta Sans + IBM Plex Mono (latin, latin-ext). */\n";
  await writeFile(resolve(FONTS_DIR, "fonts.css"), header + faces.join("\n\n") + "\n");
  console.log(`\n✓ ${faces.length} @font-face rules → fonts/fonts.css`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
